# TODO: as a team, define our own custom PMD checker so that we don't have to keep adding piecemeal
#       to this file

endpoint.uk.gov.ons.census.supporttool.CollectionExerciseEndpoint=UseVarargs
schedule.uk.gov.ons.census.supporttool.FileStager=AccessorMethodGeneration
schedule.uk.gov.ons.census.supporttool.RowStager=AccessorMethodGeneration